blank_issues_enabled: true
contact_links:
- name: Zanderlin Discord Server
  url: https://discord.com/invite/AEVsMdc9am
  about: For help with running the game, or joining the server, join our Discord server.
